### ISSUE TITLE
Notification ARN / Role ARN should be optional for lifecycle hooks. 

### ISSUE THREAD

**Issue by backjo** [keikoproj/instance-manager#177]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT
**What happened**:
Notification ARN and Role ARN are currently required fields for configuring lifecycle hooks on instance groups.
**What you expected to happen**:
These fields should be optional. Depending on the way that these hooks are consumed, these are not needed (and not required by the AWS API). One such example is leveraging AWS EventBridge to consume these events, as described in https://github.com/aws/aws-node-termination-handler

**Comment by eytan-avisror** [comment]
Hey @backjo 

Looks like RoleARN is required for the PutLifecycleHook API call according to docs:

https://docs.aws.amazon.com/sdk-for-go/api/service/autoscaling/#PutLifecycleHookInput
```
    // The ARN of the IAM role that allows the Auto Scaling group to publish to
    // the specified notification target, for example, an Amazon SNS topic or an
    // Amazon SQS queue.
    //
    // Required for new lifecycle hooks, but optional when updating existing hooks.
    RoleARN *string `min:"1" type:"string"`
```

However, I do see that the UI doesn't required it... which is strange..
Will try it out to see if I can still use PutLifecycleHook API without roles

**Comment by eytan-avisror** [comment]
I think thats just a stale comment - it doesnt have the json notation for required:true like other fields:
```
LifecycleHookName *string `min:"1" type:"string" required:"true"`
```

**Comment by eytan-avisror** [comment]
Thanks @backjo - we should be able to address this in the next release

**Comment by backjo** [comment]
@eytan-avisror should have a PR up for you here in a minute :)
