### ISSUE TITLE
Support ARM architecture

### ISSUE THREAD

**Issue by backjo** [keikoproj/instance-manager#191]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Feature Request
**What happened**:
ARM-based processors are becoming increasingly popular. We should leverage the cross-platform capabilities in Docker to build and publish images for ARM64 in addition to AMD64

**Comment by eytan-avisror** [comment]
Is the use case here that you want to run the controller using a node with an ARM64/AMD64 architecture?

**Comment by backjo** [comment]
Yep - IM already supports running ARM nodes

**Comment by eytan-avisror** [comment]
@backjo 
Is this a known practice for other projects as well? I never saw a project that publishes multiple images to support these architectures.

I assume we just want to support AMD in this case? we could definitely do it.. but need to think of naming and how to do this without affecting existing images/CI

possibly `keikoproj/instance-manager:<version>-amd64`?
we can skip this in CI completely, and only do this for release pipeline when we publish a version.

Do we also want a `:latest-amd64` ? seems a bit strange

**Comment by backjo** [comment]
@eytan-avisror all of the major cloud native ecosystem projects at least have issues for it - with more support being added every week (I believe Envoy just released their support). 

W.r.t. tags, you can actually have multiple architecture images under the same tag - see https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/. 

I've got a basic Github Actions setup - let me see if I can just add it to that and create a PR for that.

**Comment by eytan-avisror** [comment]
Oh I see, thats awesome!
We are using travis currently, so you can take a look at travisfile / dockerfile for these changes..  (if you need this compatibility now)
We will be moving to Github Actions soon
