### ISSUE TITLE
excessing creation of LaunchTemplates if ScalingGroup creation fails.

### ISSUE THREAD

**Issue by preflightsiren** [keikoproj/instance-manager#223]
**Is this a BUG REPORT or FEATURE REQUEST?**: Bug report

**What happened**: When creating an InstanceGroup with an incorrect AMI (one that doesn't exist for example), instance-manager logs the error but creates a new LaunchTemplate on each reconciliation loop.

**What you expected to happen**: Only one LaunchTemplate is created

**How to reproduce it (as minimally and precisely as possible)**: Create an InstanceGroup using LaunchTemplates with an non-existent AMI ID .

**Anything else we need to know?**: AWS incorrectly reports this error as `You are not authorized to use launch template` see https://coding-stream-of-consciousness.com/2019/12/02/aws-not-authorized-to-use-launch-template-in-terraform-or-in-console/ for some examples.

**Environment**:

- Kubernetes version:
clientVersion:
  buildDate: "2020-09-16T21:51:49Z"
  compiler: gc
  gitCommit: f5743093fd1c663cb0cbc89748f730662345d44d
  gitTreeState: clean
  gitVersion: v1.19.2
  goVersion: go1.15.2
  major: "1"
  minor: "19"
  platform: darwin/amd64
serverVersion:
  buildDate: "2020-10-20T23:27:12Z"
  compiler: gc
  gitCommit: ad4801fd44fe0f125c8d13f1b1d4827e8884476d
  gitTreeState: clean
  gitVersion: v1.16.15-eks-ad4801
  goVersion: go1.13.15
  major: "1"
  minor: 16+
  platform: linux/amd64

```bash
kubectl version -o yaml
```

**Comment by eytan-avisror** [comment]
We should definitely address any scenario where we create launch templates in an endless loop.. I think i've encountered this before when I was missing a permission in the IAM role of the controller, in my case it was `ec2:RunInstances` which is required for using launch templates.

Here is the full list:
```
iam:GetRole
iam:GetInstanceProfile
iam:PassRole
ec2:DescribeSecurityGroups
ec2:DescribeSubnets
ec2:DescribeInstanceTypeOfferings
ec2:DescribeInstanceTypes
ec2:DescribeLaunchTemplates
ec2:DescribeLaunchTemplateVersions
ec2:CreateLaunchTemplate
ec2:CreateLaunchTemplateVersion
ec2:ModifyLaunchTemplate
ec2:DeleteLaunchTemplate
ec2:DeleteLaunchTemplateVersions
ec2:RunInstances
autoscaling:CreateOrUpdateTags
autoscaling:DeleteTags
autoscaling:SuspendProcesses
autoscaling:ResumeProcesses
autoscaling:DescribeAutoScalingGroups
autoscaling:UpdateAutoScalingGroup
autoscaling:TerminateInstanceInAutoScalingGroup
autoscaling:DescribeLaunchConfigurations
autoscaling:CreateLaunchConfiguration
autoscaling:DeleteLaunchConfiguration
autoscaling:DeleteAutoScalingGroup
autoscaling:CreateAutoScalingGroup
autoscaling:DescribeLifecycleHooks
autoscaling:DeleteLifecycleHook
autoscaling:PutLifecycleHook
autoscaling:EnableMetricsCollection
autoscaling:DisableMetricsCollection
eks:CreateNodegroup
eks:DescribeNodegroup
eks:DeleteNodegroup
eks:UpdateNodegroupConfig
eks:DescribeCluster
```

Can you make sure you have those permissions?
