### ISSUE TITLE
Prometheus Metrics Integration

### ISSUE THREAD

**Issue by eytan-avisror** [keikoproj/instance-manager#238]
We should expose a prometheus endpoint and provide metrics.

- Instance Group per State - gauge that shows instance groups and their state
- Failed Reconcile - counter that shows number of failed reconcile events
- Successful Reconcile - counter that shows number of successful reconcile events
- Node Rotation - show last instance group upgrade per instance group
- AWS Throttling - counter of throttled calls
- AWS Cache - show cache miss/hits

**Comment by shrinandj** [comment]
This is awesome!
