### ISSUE TITLE
Support warm pools

### ISSUE THREAD

**Issue by eytan-avisror** [keikoproj/instance-manager#277]
ASGs support provisioning pre warmed instances to make scaling faster.
This could be pretty useful if it cuts down the autoscaling time.

We should explore both running/stopped option for pre-warmed instances and support this API if it makes sense

https://docs.aws.amazon.com/sdk-for-go/api/service/autoscaling/#AutoScaling.PutWarmPool

- [x] AL2 Support
- [x] Windows Support
- [ ] Bottlerocket Support

**Comment by backjo** [comment]
It'd be interesting to compare this to the existing startup time - it's around 90-120 seconds for us on our BottleRocket nodes.

Though, it looks like it might not work right now for us:
`Warm pools currently can't be used with ECS, EKS, and self-managed Kubernetes.`

**Comment by eytan-avisror** [comment]
I just tested it in stopped mode, and it works! got nodes to join within few seconds of scale event.. not sure why they say it's not supported 🤣  need to see exactly what is not supported

**Comment by eytan-avisror** [comment]
Pre warmed stopped instance - 1m 20s from pod scale event, to node ready
No pre-warming - 1m 50s - so it potentially shaves a cool 30s off of your scaling time
so around ~30% faster 

Not much, but nice improvement if you have very peaky traffic

**Comment by eytan-avisror** [comment]
One corner case we need to work around somehow, is that when the warm pool instances are started they briefly join the cluster and then when they are stopped they leave.
The problem cases I've seen is when:
- They go to ready for some time (this may cause scheduling)
- The node objects sometime stick around as NotReady after the instance is stopped

Ideal solution would have a way to not run the bootstrap script on the prewarmed instances, and only run it when scaling happens.

I am experimenting with using some simple script addition in userdata to be able to do that e.g.
```
INSTANCE_ID=$(curl http://169.254.169.254/latest/meta-data/instance-id)
LIFECYCLE=$(aws autoscaling describe-auto-scaling-instances --region us-west-2 --instance-id $INSTANCE_ID | jq ".AutoScalingInstances[].LifecycleState")

if grep -q "$LIFECYCLE" <<< "Warmed"; then
  exit 0
fi

## Bootstrap script below
```

But this would mean granting every node access to DescribeAutoscalingInstances which might be problematic

**Comment by eytan-avisror** [comment]
Reached out to AWS, now the docs say:
```
If you try using warm pools with Amazon Elastic Container Service (Amazon ECS) or Elastic Kubernetes Service (Amazon EKS) managed node groups, there is a chance that these services will schedule jobs on an instance before it reaches the warm pool. 
```
🤣 

So the issue we need to work around is the instances becoming ready for few seconds while they get warmed.

Ideal solution would be to somehow not bootstrap the nodes on warming, only on scaling.

**Comment by eytan-avisror** [comment]
Here is how we are able to work around current limitations:

Add the following conditional template to userdata:
```bash
## Only if spec has warm pool configured this section will be added - this means userdata change when enabling warmPool, we should reevaluate whether we must have this templated or can keep it static.
{{- if .HasWarmPool}}

## This requires the AMI having awscli + jq, or install it in a prebootstrap step. if it's not installed this section will be skipped and we always bootstrap the node.
if [[ $(type -P $(which aws)) ]] && [[ $(type -P $(which jq)) ]] ; then
   
        ## Get InstanceID, Region, and Lifecycle Stage - getting lifecycle requires adding extra permissions on the node, would be nice if we can find a way to figure out lifecycle without adding access to DescribeAutoScalingInstances

	INSTANCE_ID=$(curl http://169.254.169.254/latest/meta-data/instance-id)
	REGION=$(curl http://169.254.169.254/latest/meta-data/placement/region)
	LIFECYCLE=$(aws autoscaling describe-auto-scaling-instances --region $REGION --instance-id $INSTANCE_ID | jq ".AutoScalingInstances[].LifecycleState")
	echo $INSTANCE_ID, $REGION, in state: $LIFECYCLE

       ## If the lifecycle stage of the node is *Warmed*, we delete the userdata state file and exit without bootstrapping
	if [[ $LIFECYCLE == *"Warmed"* ]]; then
                ## By removing this file we guarantee the next bootup (when scaling happens), and the lifecycle is no longer *Warmed*, we will run userdata once again and this time, bootstrap
		rm /var/lib/cloud/instances/$INSTANCE_ID/sem/config_scripts_user
		exit 0
	fi
fi
{{- end}}
```

This workaround works perfectly, the design cost however is:
- Extra node rotation when enabling feature (need to evaluate making block static)
- Adding access to every node for `DescribeAutoScalingInstances`, we can make the controller add this in case the IAM role is managed by controller and WarmPool is configured, but it's still extra permission to give every node.

#### TBD:
- Need to work on upgrade scenario, in this case we can detect if the warm pool instances' launch config/template mismatches from the scaling config, and delete the warm pool if that is the case before we proceed to rotate the nodes, the next reconciles will recreate the node pool with the new launch config/template.
** If this is not handled, the nodes terminated in the scaling group, cause instances from the warm pool to join instead which still have the old launch configuration - this actually makes the upgrade process longer.

**Comment by backjo** [comment]
A good read on how Kops integrated warm pools - https://dev.to/olemarkus/blazing-fast-kubernetes-scaling-with-asg-warm-pools-53bd

**Comment by eytan-avisror** [comment]
@backjo funny I thought we were on the bleeding edge of trying this out 🤣 

They use the same approach basically of looking at LifecycleState and checking if it has "Warming" as prefix.
The difference is that Kops uses nodeup as a systemd to handle bootstrapping, and on eks we have the bootstrapping.sh script which is called in userdata.

**Comment by backjo** [comment]
I thought so too!

Yeah, pretty much - and since we have 3 different bootstrap methods (AL2/BottleRocket/Windows) - there will be 3 different places where startup changes need to happen.

**Comment by eytan-avisror** [comment]
> I thought so too!
> 
> Yeah, pretty much - and since we have 3 different bootstrap methods (AL2/BottleRocket/Windows) - there will be 3 different places where startup changes need to happen.

Yeah, we can totally do that, I guess the most annoying part is adding DescribeAutoScalingInstances to all nodes & depending on awscli / jq (we will have to possibly do something else on Windows machines)

**Comment by eytan-avisror** [comment]
I wonder if another approach is to vend a small binary similar to Kops, however we would need to come up with a mechanism to get that binary from the node (they use S3 buckets I think).

**Comment by eytan-avisror** [comment]
@backjo is this even possible with bottlerocket TOML style user-data? Can we run an arbitrary script on bottlerocket?

**Comment by backjo** [comment]
Not out of the box - there's a few levers we can pull, namely [bootstrap containers](https://github.com/bottlerocket-os/bottlerocket/blob/328b50aa489bd6c7d386ea7ad0790ec39d2a9ca9/sources/api/bootstrap-containers/src/main.rs).

**Comment by eytan-avisror** [comment]
PR out for AL2 support, we should also add Windows support

**Comment by eytan-avisror** [comment]
@backjo do you want to leave this open to explore bottlerocket support, or do you feel like this makes less sense? if it doesnt make much sense for bottlerocket we can close this issue

**Comment by sam-goodwin** [comment]
Great work figuring this all out! 

I am trying to determine what is the best configuration for an elastically auto-scaling EKS cluster and stumbled across instance-manager through this blog: https://medium.com/keikoproj/rapid-auto-scaling-on-eks-part-2-d094b9b2cd62 which states that it takes roughly 90s for a Node to become available with instance-manager warm pools.

Is that still true, or can we make it faster? Do you know where that time is being spent?

> PR out for AL2 support, we should also add Windows support

I see support was added for both AL2 and Windows, is there a plan to add support for Bottlerocket? I'd assume that Bottlerocket would boot faster but haven't confirmed that or measured how significant it is.
