### ISSUE TITLE
Log messages do not indicate which IG they're for

### ISSUE THREAD

**Issue by shrinandj** [keikoproj/instance-manager#34]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

**What happened**:
- Create 2 or more instance-groups.
- Watch the logs of the instance-manager.
- The log looked something like this:
```
time="2019-08-31T03:51:07Z" level=info msg="stack state: CREATE_IN_PROGRESS"
```
- It's unclear which IG the above message was for.

**What you expected to happen**:
It should be possible to know which IG the log messages are for.

**Comment by eytan-avisror** [comment]
The identity is higher in the block, example:
(see resource name and resource namespace)
```
time="2019-08-28T20:49:25Z" level=info msg="resource document version: 1926714"
time="2019-08-28T20:49:25Z" level=info msg="resource namespace: instance-manager"
time="2019-08-28T20:49:25Z" level=info msg="resource name: bdd-test-crd"
time="2019-08-28T20:49:25Z" level=info msg="resource provisioner: eks-cf"
time="2019-08-28T20:49:25Z" level=info msg="upgrade strategy: crd"
time="2019-08-28T20:49:26Z" level=info msg="state transitioned to: Init"
time="2019-08-28T20:49:26Z" level=info msg="starting cloud discovery"
time="2019-08-28T20:49:27Z" level=info msg="stack state: CREATE_COMPLETE"
time="2019-08-28T20:49:27Z" level=info msg="starting state discovery"
time="2019-08-28T20:49:27Z" level=info msg="state transitioned to: InitUpdate"
time="2019-08-28T20:49:27Z" level=info msg="starting update"
time="2019-08-28T20:49:27Z" level=info msg="update not required"
time="2019-08-28T20:49:27Z" level=info msg="state transitioned to: ReconcileModified"
time="2019-08-28T20:49:28Z" level=info msg="stack state: CREATE_COMPLETE"
time="2019-08-28T20:49:28Z" level=info msg="starting bootstrap"
time="2019-08-28T20:49:28Z" level=info msg="state transitioned to: Ready"
time="2019-08-28T20:49:28Z" level=info msg="reconcile completed"
2019-08-28T20:49:28.231Z	DEBUG	controller-runtime.controller	Successfully Reconciled	{"controller": "instancegroup", "request": "instance-manager/bdd-test-crd"}
```

**Comment by eytan-avisror** [comment]
Leaving this issue open so we can make logging better, right now it's throwing out a lot of messages for every reconcile.
Ideally we should have one message per reconcile with the identity of the instance group.

**Comment by shrinandj** [comment]
Is it guaranteed that if there are two IGs being processed concurrently, their log messages will not get intermingled?

Can the resource-name be just part of each log message so that the additional lookup is not required (and therefore is `grep` friendly)?

**Comment by eytan-avisror** [comment]
events are received by controller async (via watch), but each reconcile happens sequentially so logs do not get mingled.

I will look into a better logging model that also includes resource name in every message

**Comment by dthomson25** [comment]
Won't the logs become intermingled if you have multiple workers though? Each worker handles one reconciliation at a time, but the work queue will ensure that you are not working on the same resource.

**Comment by eytan-avisror** [comment]
@dthomson25 this is using kubebuilder scaffolding, to my knowledge there is a single 'worker', but I may be wrong.
Reconciles are very fast because we don't wait during the reconcile, every reconcile re-evaluates.
It's possible that more workers are added when there are many objects reconciling - worth checking if this is the case.

**Comment by dthomson25** [comment]
Per https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/internal/controller/controller.go#L50-L51, it looks like the number is configurable, and the default is 1.

**Comment by eytan-avisror** [comment]
We need to refactor logging to use json format as well. this will be prioritized for next release
