### ISSUE TITLE
Support managed worker node group for EKS

### ISSUE THREAD

**Issue by shrinandj** [keikoproj/instance-manager#69]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

**What happened**:
AWS now supports managed worker [nodegroups](https://docs.aws.amazon.com/eks/latest/userguide/managed-node-groups.html). These are not currently supported by instance-manager.

**What you expected to happen**:
It should be possible to create/read/update/delete these managed node groups as IGs.

**Anything else we need to know?**:
There are CFNs for provisioning of managed node group: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-nodegroup.html

Other links:
Upgrades: https://docs.aws.amazon.com/eks/latest/userguide/update-managed-node-group.html

**Comment by eytan-avisror** [comment]
Nice! we should try this out
