### ISSUE TITLE
EPIC: Fargate Support 

### ISSUE THREAD

**Issue by thomaswhitcomb** [keikoproj/instance-manager#70]
**Is this a BUG REPORT or FEATURE REQUEST?**:

Feature Request

**What happened**:

Amazon announced Fargate support for EKS.  Now pods can be scheduled via Fargate.

**What you expected to happen**:

Pods within a namespace (and optional tags) can be automatically scheduled to run via Fargate.  Users should be able to create, modify and delete Fargate support.

**Anything else we need to know?**:

https://docs.aws.amazon.com/eks/latest/userguide/fargate.html
https://docs.aws.amazon.com/eks/latest/userguide/fargate-profile.html

**Comment by edlee2121** [comment]
We should integrate this with instance manager on IKS2. That is, a node group could be implemented using Fargate. Please keep this issue updated as we learn now to best integrate Fargate with IKS2.

**Comment by thomaswhitcomb** [comment]
Yeah, I created an issue in https://github.com/keikoproj/instance-manager
and was thinking it will be implemented as another provisioner
(eks-fargate).  I am working on the spec now and will create an early PR
for the readme before i start writing code.

**Comment by eytan-avisror** [comment]
Ref #71 

Once this initial implementation is in we should start opening issues and link them here.

**Comment by eytan-avisror** [comment]
Closing this for now as we have basic fargate support, we can create more stories in the future should we want to improve the existing implementation
